/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Payments {
  amount_cents: number;
  asaas_payment_id: string | null;
  changed_by: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  kind: Generated<string>;
  method: string;
  raw_last_event: Json | null;
  reservation_id: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface RateOverrides {
  closed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<number>;
  min_stay: number | null;
  price_cents: number | null;
  room_id: number;
  units_available: number | null;
  updated_at: Generated<Timestamp>;
}

export interface ReservationBalances {
  amount_paid_cents: Int8 | null;
  balance_due_cents: Int8 | null;
  code: string | null;
  reservation_id: number | null;
  total_cents: number | null;
}

export interface ReservationExtras {
  amount_cents: number;
  concept: string;
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<number>;
  reservation_id: number;
}

export interface ReservationNights {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  night: Timestamp;
  reservation_id: number;
  room_unit_id: number;
}

export interface Reservations {
  babies: Generated<number>;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: number | null;
  check_in: Timestamp;
  check_out: Timestamp;
  checked_in_at: Timestamp | null;
  checked_in_by: number | null;
  checked_out_at: Timestamp | null;
  checked_out_by: number | null;
  children: Generated<number>;
  children_ages: Generated<number[]>;
  code: string | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  deposit_cents: number | null;
  expires_at: Timestamp | null;
  guest_email: string | null;
  guest_name: string | null;
  guest_phone: string | null;
  guests: number;
  id: Generated<number>;
  notes: string | null;
  origin: Generated<string>;
  override_total_cents: number | null;
  room_id: number;
  room_unit_id: number | null;
  status: Generated<string>;
  total_cents: number;
  updated_at: Generated<Timestamp>;
}

export interface RoomRates {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  occupancy: number;
  room_id: number;
  updated_at: Generated<Timestamp>;
  weekday_cents: number;
  weekend_cents: number;
}

export interface Rooms {
  active: Generated<boolean>;
  adults_only: Generated<boolean>;
  capacity: number;
  created_at: Generated<Timestamp>;
  default_min_stay: Generated<number>;
  description: string | null;
  id: Generated<number>;
  name: string;
  pets_allowed: Generated<boolean>;
  sort_order: Generated<number>;
  total_units: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface RoomUnits {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  label: string;
  notes: string | null;
  room_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_used_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: number;
}

export interface Settings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  password_hash: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  payments: Payments;
  pgmigrations: Pgmigrations;
  rate_overrides: RateOverrides;
  reservation_balances: ReservationBalances;
  reservation_extras: ReservationExtras;
  reservation_nights: ReservationNights;
  reservations: Reservations;
  room_rates: RoomRates;
  room_units: RoomUnits;
  rooms: Rooms;
  sessions: Sessions;
  settings: Settings;
  users: Users;
}
