/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface RateOverrides {
  closed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<number>;
  min_stay: number | null;
  price_cents: number | null;
  room_id: number;
  units_available: number | null;
  updated_at: Generated<Timestamp>;
}

export interface Reservations {
  check_in: Timestamp;
  check_out: Timestamp;
  code: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  guest_email: string | null;
  guest_name: string | null;
  guest_phone: string | null;
  guests: number;
  id: Generated<number>;
  notes: string | null;
  room_id: number;
  status: Generated<string>;
  total_cents: number;
  updated_at: Generated<Timestamp>;
}

export interface RoomRates {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  occupancy: number;
  room_id: number;
  updated_at: Generated<Timestamp>;
  weekday_cents: number;
  weekend_cents: number;
}

export interface Rooms {
  active: Generated<boolean>;
  capacity: number;
  created_at: Generated<Timestamp>;
  default_min_stay: Generated<number>;
  description: string | null;
  id: Generated<number>;
  name: string;
  pets_allowed: Generated<boolean>;
  total_units: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  pgmigrations: Pgmigrations;
  rate_overrides: RateOverrides;
  reservations: Reservations;
  room_rates: RoomRates;
  rooms: Rooms;
}
