/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface RateOverrides {
  closed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<number>;
  min_stay: number | null;
  price_cents: number | null;
  room_id: number;
  updated_at: Generated<Timestamp>;
}

export interface RoomRates {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  occupancy: number;
  room_id: number;
  updated_at: Generated<Timestamp>;
  weekday_cents: number;
  weekend_cents: number;
}

export interface Rooms {
  active: Generated<boolean>;
  capacity: number;
  created_at: Generated<Timestamp>;
  default_min_stay: Generated<number>;
  description: string | null;
  id: Generated<number>;
  name: string;
  pets_allowed: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  pgmigrations: Pgmigrations;
  rate_overrides: RateOverrides;
  room_rates: RoomRates;
  rooms: Rooms;
}
